### ISSUE TITLE
{"errors":[{"message":"SSL is required","code":92}]}

### ISSUE THREAD

**Issue by nhoizey** [rob-murray/jekyll-twitter-plugin#11]
This is the content of the cache file, and I don't know what to do with this error.

Thanks.

**Comment by rob-murray** [comment]
Hi, 
I presume that is not the tweet you were expecting :)

That is a strange error though and at first glance appears to be something from the Twitter API - I have not seen this before.

Could you let me know which version of Twitter gem you have (if you look at the dependency chain for this gem in `Gemfile.lock` and the Tweet url please and I will see if I can replicate this problem. Also just open up the tweet url in a browser and check its not protected or anything.

**Comment by nhoizey** [comment]
I have this:

```
    jekyll-twitter-plugin (1.3.0)
      twitter (~> 5.11)
```

But also this:

```
    twitter (5.14.0)
      addressable (~> 2.3)
      buftok (~> 0.2.0)
      equalizer (~> 0.0.9)
      faraday (~> 0.9.0)
      http (~> 0.6.0)
      http_parser.rb (~> 0.6.0)
      json (~> 1.8)
      memoizable (~> 0.4.0)
      naught (~> 1.0)
      simple_oauth (~> 0.3.0)
```

This is the tweet I'm trying to use: https://twitter.com/csswg/status/571742414299246592

**Comment by rob-murray** [comment]
Thanks - I will see if I can replicate the problem.

If you delete the specific cache file for that Tweet and run Jekyll again does the same thing occur?

**Comment by nhoizey** [comment]
Yes, it does.

**Comment by rob-murray** [comment]
How are you calling the plugin from your jekyll post? This error actually looks like the problem with the original plugin, see issue https://github.com/scottwb/jekyll-tweet-tag/issues/9.

This plugin needs the tag in the format below.

```
{% twitter oembed status_url *options %}
```

Rather than the original plugin: `{% tweet https://twitter.com/DEVOPS_BORAT/statuses/159849628819402752 %}` - I used a different tag name to differentiate between this one and the other in case that was ever resurrected.

**Comment by nhoizey** [comment]
OMG, sorry, I was still using `tweet` instead of `twitter`! :-/

**Comment by rob-murray** [comment]
No problem; sorry I didnt remember the error!

**Comment by nhoizey** [comment]
No problem… ;-)

While we're here, do you plan to add other API types? Maybe `oembed` could be the default, so that we don't have to write it for every tweet… ;-)

**Comment by rob-murray** [comment]
I thought I might add more types of Twitter content which is why this uses the Twitter gem and the type is an argument - but so far the need has not occurred so I could remove it and make the `oembed` function the default. Will add it as an issue!

**Comment by nhoizey** [comment]
Great, thanks!
