### ISSUE TITLE
jekyll-twitter-plugin works locally but not with Github Pages

### ISSUE THREAD

**Issue by tim-peterson** [rob-murray/jekyll-twitter-plugin#15]
Just got an email from Github with the following message:

```
The tag `twitter` in `_posts/xxxx-xxxx-xxxxx/#excerpt` is not a recognized Liquid tag.
```

Bummer.

**Comment by rob-murray** [comment]
Yeah I think Github runs Jekyll in "safe-mode", that is without any plugins that could execute arbitrary code when they build the site. The last time I checked the work-around was to build the HTML locally and then merge that generated content into the `gh-pages` branch but there may be something better now.
