### ISSUE TITLE
Auto detect tweet URL in Markdown files

### ISSUE THREAD

**Issue by nhoizey** [rob-murray/jekyll-twitter-plugin#16]
Even better than #12, it would be nice if we could set the plugin to find tweet URLs in Markdown files without any specific syntax.

Inspired by https://github.com/takuti/jekyll-lazy-tweet-embedding/blob/master/lazy_tweet_embedding.rb

**Comment by rob-murray** [comment]
Nice idea, I will have a look at that code.

I would expect this if implemented to be in addition to explicitly specifying the Tweet via the tag.

**Comment by nhoizey** [comment]
I agree it's an additional feature, at least for forward compatibility, and it might even be activated only via a setting

**Comment by rob-murray** [comment]
I've had a look at the code to implement this and it's not an option I want to add to this library:

* I'm happy with the latest API of this library, it is versatile in that it supports lots of options via the Twitter embed APIs and that it is explicit when embedding a Tweet, Timeline, etc. The markup is minimal enough for my taste.
* The code to implement this automagical feature is a bit different to that necessary to add a tag and I'd prefer not to have to maintain anything extra.

**Comment by nhoizey** [comment]
Well, I still think it would have been interesting, but I understand.

I will now use the plugin I mentioned in the initial issue description.
