### ISSUE TITLE
Twitter options does not work

### ISSUE THREAD

**Issue by banterCZ** [rob-murray/jekyll-twitter-plugin#22]
It seems to me that Twitter options (conversation) does not work or I did not understand how to configure it. When I use

`{% twitter https://twitter.com/Split82/status/766572568585404420 conversation=none %}`

I still see the conversation. I have tried to clear the twitter cache but with no effect.

<img width="532" alt="tweet" src="https://cloud.githubusercontent.com/assets/1705996/22800777/c351000e-ef0a-11e6-9e1b-db8785edd476.png">

**Comment by rob-murray** [comment]
Hi,
After a bit of digging and trial and error it looks like `hide_thread=true` seems to work - I have no idea why, could be that the Twitter API actually used is subtly different to the documentation. I will update the link in this README to point one of the links below.

Documentation I found: https://dev.twitter.com/web/embedded-tweets https://dev.twitter.com/rest/reference/get/statuses/oembed

**Comment by banterCZ** [comment]
Perfect, it is working. Thanks!

**Comment by rob-murray** [comment]
👍
