### ISSUE TITLE
Using variable?

### ISSUE THREAD

**Issue by jeekajoo** [rob-murray/jekyll-twitter-plugin#23]
Hello,
I'm trying to use variable (for my example: page.tweet) without luck. What I tried:

**method 1**
```
{% include tweet.html
  tweet = page.tweet
%}
```

tweet.html:
```
{% twitter include.tweet align='center' %}
```

**method 2**
```
{% twitter page.tweet align='center' %}
```

Thank you

**Comment by rob-murray** [comment]
Hi, 
Sorry for such a slow response.

I will have a look at this - not something I have done before.

Why do you need to store the tweet as a variable?

Rob

**Comment by jeekajoo** [comment]
> Why do you need to store the tweet as a variable?

This way, you can reuse code `{% twitter page.tweet align='center' %}`.

**Comment by rob-murray** [comment]
Why would you do that? The tweet would be formatted based on any params provided by the Twitter API so it would not be easy to change those. The Twitter API response is cached to a file so there may be a small performance improvement here.

**Comment by jeekajoo** [comment]
`page.tweet` is just a [custom front matter](http://jekyllrb.com/docs/frontmatter/) storing the URL of the tweet.

**Comment by rob-murray** [comment]
I see, ok will take a look

**Comment by mtully** [comment]
Another benefit would be to use an array of tweet URLs in your variable. For example, loop over an array of page variables and show multiple tweets. Example:

```html
---
tweets:
- https://twitter.com/user_name/status/123
- https://twitter.com/user_name/status/456
---

{% if page.tweets %}

<div class="tweets">
  {% for tweet in page.tweets %}

  <div id="tweet-{{ forloop.index }}" class="tweet">
    {% twitter {{ tweet }} %}
  </div>

  {% endfor %}
</div>

{% endif %}

```
