### ISSUE TITLE
Jekyll won't build when trying to use the plugin

### ISSUE THREAD

**Issue by Ben-TangentDesign** [rob-murray/jekyll-twitter-plugin#24]
Hi,
After successful installing the plugin it seems every time i actually try and use the plugin i get the following error:

Liquid Exception: SSL_connect returned=1 errno=0 state=error: certificate verify

Any ideas why this would be the case?

**Comment by rob-murray** [comment]
Please could you let me know what version of Ruby and OpenSSL (& how its installed - rbenv, rvm)?

This is usually an issue with OpenSSL lacking root certs and so it does not trust the Twitter SSL certificate - assuming they are presenting a valid cert and there is no man in the middle attack going on 😄 

What is the output from these commands?

```
ruby -rnet/https -e "Net::HTTP.get URI('https://google.com')"

ruby -ropenssl -e "puts OpenSSL::OPENSSL_VERSION"
ruby -ropenssl -e "puts OpenSSL::OPENSSL_LIBRARY_VERSION"
```

**Comment by Ben-TangentDesign** [comment]
C:/tools/ruby23/lib/ruby/2.3.0/net/http.rb:933:in `connect_nonblock': SSL_connect returned=1 errno=0 state=error: certificate verify failed (OpenSSL::SSL::SSLError)
        from C:/tools/ruby23/lib/ruby/2.3.0/net/http.rb:933:in `connect'
        from C:/tools/ruby23/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
        from C:/tools/ruby23/lib/ruby/2.3.0/net/http.rb:852:in `start'
        from C:/tools/ruby23/lib/ruby/2.3.0/net/http.rb:584:in `start'
        from C:/tools/ruby23/lib/ruby/2.3.0/net/http.rb:479:in `get_response'
        from C:/tools/ruby23/lib/ruby/2.3.0/net/http.rb:456:in `get'
        from -e:1:in `<main>'

OpenSSL 1.0.2j  26 Sep 2016 (for other commands)

**Comment by rob-murray** [comment]
Can you try updating Ruby's OpenSSL library CA cert by something like this:

`curl -fsSL curl.haxx.se/ca/cacert.pem \
  -o "$(ruby -ropenssl -e 'puts OpenSSL::X509::DEFAULT_CERT_FILE')"`

This just downloads the file https://curl.haxx.se/ca/cacert.pem to wherever OpenSSL stores its cert file.

I'm not on Windows so I dont have any way to test this though.

**Comment by Ben-TangentDesign** [comment]
Apologies i had a type in the system environment variable. Apologies again

**Comment by jerm09** [comment]
@rob-murray  I am getting the same error what was it that you changed to get it to work  @Ben-TangentDesign
