### ISSUE TITLE
Toggle data cards option

### ISSUE THREAD

**Issue by nickjj** [rob-murray/jekyll-twitter-plugin#26]
If you manually set `<blockquote class="twitter-tweet" data-cards="hidden">` it will hide data cards. Is there any way to pass that into the `{% twitter %}` tag?

If I try to edit the cached version to include that, then it just writes out a new cache file and ignores the modified version.

**Comment by rob-murray** [comment]
Normally you would just pass `cards=hidden` as a parameter as described in the README but this does not seem to work as stated [here](https://dev.twitter.com/web/embedded-tweets/parameters). If you use the `hide_media=true` from the [oembed api reference](https://dev.twitter.com/rest/reference/get/statuses/oembed) then that seems to work.

As mentioned in issue #25 the cached file is not intended to be edited.
