### ISSUE TITLE
Twitter search?

### ISSUE THREAD

**Issue by lisah2u** [rob-murray/jekyll-twitter-plugin#29]
I was hoping hashtag search would work, such as:

{% twitter https://twitter.com/hashtag/catz limit=5 %}

However, the response provided is something like this:
There was a 'Not Found' error fetching URL: 'https://twitter.com/hashtag/catz'

**Comment by rob-murray** [comment]
Hi, it does not look like the [Twitter oEmbed API supports search URLs](https://dev.twitter.com/web/embedded-timelines/oembed) for some reason - I haven't been able to find a way to do this yet. 

The other way to add a hashtag search is using the [search widget thing](https://dev.twitter.com/web/embedded-timelines/search) which is a bit annoying, definitely would be useful to be able use the oEmbed API for this.
