### ISSUE TITLE
Can be used in Github pages?

### ISSUE THREAD

**Issue by galex** [rob-murray/jekyll-twitter-plugin#32]
Hello,

I added manually this plugin to my jekyll blog, but when commited to github I get an error:

`The tag `twitter` on line 5 in `_posts/xxx.md` is not a recognized Liquid tag. For more information, see https://help.github.com/articles/page-build-failed-unknown-tag-error/.`

I thought as this is a liquid plugin it would work, but it doesn't. What am I missing here?

Thank you in advance,
Alex

**Comment by samkap** [comment]
I got the same error as @galex and it would be great if someone had a solution!

**Comment by melaniewalsh** [comment]
I'm also having this issue and would like to echo the wish for a solution!

**Comment by daimz** [comment]
I'm having the exact same problem. Would love to know if someone has a solution.

**Comment by rob-murray** [comment]
Sorry, not that I know of - basically they run in "safe" mode so they dont allow any untrusted server-side code to run.

https://github.com/rob-murray/jekyll-twitter-plugin/issues/15#issuecomment-122787785
