### ISSUE TITLE
Implementing twitter 

### ISSUE THREAD

**Issue by utkarshjain30** [rob-murray/jekyll-twitter-plugin#37]
I am using the Manual process to implement twitter

I have followed the following steps

$ mkdir -p _plugins && cd _plugins
$ wget https://raw.githubusercontent.com/rob-murray/jekyll-twitter-plugin/master/lib/jekyll-twitter-plugin.rb

And I also added 
plugins: ['jekyll-twitter-plugin'] ---> this in _config.yml

I also added the following piece of code in my index.html

{% twitter https://twitter.com/jekyllrb maxwidth=500 limit=5 %}

But nothing seems to be work on my local machine

**Comment by CharlemagneVI** [comment]
The manual import says its deprecated, I used the gem installation route, but still get Liquid Exceptions for  undefined method `key?` when I try to use the twitter tags.

**Comment by rob-murray** [comment]
The manual import should still work but I can't guarantee that and is easier to use the proper plugin method.

If you use the plugin method though, the library must be available either add to your gemfile or install it globally, however you have jekyll set up.
