### ISSUE TITLE
Can't get plugin to work

### ISSUE THREAD

**Issue by ryanburnette** [rob-murray/jekyll-twitter-plugin#7]
I've been troubleshooting for about an hour now and I can't get the plugin to work at all. I've double-checked that my credentials are correct and that the links I'm trying to oembed are correct.

I'll update this issue if I can find anything but I wanted to see if I was the only one dead in the water on v1.2.0.

**Comment by ryanburnette** [comment]
Same issue on v1.1.1. So it must be something on my end.

**Comment by ryanburnette** [comment]
Doh. Misspelled `oembed`. One of those days.

**Comment by rob-murray** [comment]
Lol. We've all done something similar!
Maybe there should be some logging; "Rendering tweet blah... from cache/api", if you dont see it then something has not worked.

**Comment by ryanburnette** [comment]
I don't think that's necessary. Sleep, however, is necessary.

This isn't related to the issue, but I was curious. I have another Jekyll plugin that I want to use the Cacheable class you have in use on this plugin. I was reading it over and it looks like it caches forever, or until you manually the `.tweet-cache` directory. Is that correct?

**Comment by rob-murray** [comment]
Yes, that what this does at the moment - I copied most of it from the previous plugin but my thinking was that Tweets dont change much so that shouldnt be a problem for the `oembed` usage. When another feature comes along that can be cached but needs 'refreshing', such as a timeline, then I was going to work out how to expire the cache.

**Comment by ryanburnette** [comment]
Well it's working beautifully for my embed.ly plugin. I forked this but
it's changed quite a bit from the original now
https://github.com/ryanburnette/jekyll-embedly-plugin
