### ISSUE TITLE
Embedding Tweets works fine but inserts a line of unwanted HTML

### ISSUE THREAD

**Issue by derdennis** [rob-murray/jekyll-twitter-plugin#9]
Hi Rob,

I searched for an easy way to embed Tweets into my Octopress/Jekyll blog and your plugin was really easy to install and set up. 

Only problem I have is a line of HTML after each embedded tweet reading:

```
<script async src=”//platform.twitter.com/widgets.js” charset=”utf-8”>
```

The copy & pasted HTML from Safaris Source view is:

```
<div class="embed twitter"><blockquote class="twitter-tweet"><p>jekyll-twitter-plugin (1.0.0): A Liquid tag plugin for Jekyll that renders Tweets from Twitter API <a href="http://t.co/m4EIQPM9h4">http://t.co/m4EIQPM9h4</a></p>&mdash; RubyGems (@rubygems) <a href="https://twitter.com/rubygems/status/518821243320287232">October 5, 2014</a></blockquote>
&lt;script async src=&#8221;//platform.twitter.com/widgets.js&#8221; charset=&#8221;utf-8&#8221;&gt;</div>
```

Here is a screenshot of the problem:

![embedded_tweet_screenshot](https://cloud.githubusercontent.com/assets/318414/5746536/8766d4b2-9c30-11e4-881e-a5f02a1ab321.png)

I am running OS X 10.10 and Ruby 1.9.3 via rbenv.

Is there some way to get rid of this last line? Did you see something like this before?

Regards

Dennis

**Comment by derdennis** [comment]
Hello again,

well, sorry for the trouble, solved it myself by [RTFM](https://blog.twitter.com/2014/pro-tip-for-embedding-tweets-use-the-oembed-api-endpoint).

Using  `omit_script='true'` as an option removes the line from the HTML-output. Seems the widget.js gets embedded somewhere else...

Added the option to the `args`-array to get this behavior by default by using  `args << "omit_script='true'"`.

Thank you again for this nice plugin, regards

Dennis

**Comment by rob-murray** [comment]
Cool, thanks - I have not seen that option before but yeah useful if you already have the js in your page.
